### ISSUE TITLE
issue in sending mail

### ISSUE THREAD

**Issue by k2d2soft** [karliuka/m2.Smtp#1]
Hi we have added this extension.
Every thing is install successfully.
But its not working. when we submit test commend we got successful message. but we did not receive email.

Please help me out to install the same.

<img width="955" alt="coralhaze" src="https://user-images.githubusercontent.com/43708736/46249747-172a3200-c44c-11e8-852c-f83cd6bec631.PNG">

**Comment by karliuka** [comment]
All is correct.
The module does not send a test email. It only checks the connection. After the AUTN command, the module resets the test connection.
If the connection test is successful, then magento emails are usually sent.
